apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ephemeralvolumeclaims.primed.io
spec:
  scope: Namespacedn
  group: primed.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: EphemeralVolumeClaim
    plural: ephemeralvolumeclaims
    singular: ephemeralvolumeclaim
    shortNames:
      - evcs
      - evc